function LTERsamplelog = fxn_spectra_importLTER_sample_log(workbookFile, sheetName, dataLines)
%Taylor Crockford Mar 17, 2024 - import LTER_sample_log.xlsx and pull columns for cdom and Ap rpcoessing
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%NEED TO EDIT DATALINE VARIABLE WHEN SAMPLE LOG GETS VERY LONG
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%IMPORTFILE Import data from a spreadsheet
%  LTERSAMPLELOG = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  LTERSAMPLELOG = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  LTERSAMPLELOG = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  LTERsamplelog = importfile("\\sosiknas1\Lab_data\LTER\LTER_sample_log.xlsx", "Sample_log", [1, 3344]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Mar-2024 20:23:29

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 10000];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 47);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":AU" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Cruise", "DateUTC", "StartTimeUTC", "StationDepth", "LTERStation", "CastType", "Cast", "Niskin", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Apvol", "apfilename", "adfilename", "cdomY", "cdomfilename", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var45", "Var46", "Comments"];
opts.SelectedVariableNames = ["Cruise", "DateUTC", "StartTimeUTC", "StationDepth", "LTERStation", "CastType", "Cast", "Niskin", "Apvol", "apfilename", "adfilename", "cdomY", "cdomfilename", "Comments"];
opts.VariableTypes = ["categorical", "double", "double", "double", "double", "categorical", "double", "double", "char", "char", "char", "char", "char", "char", "char", "double", "categorical", "categorical", "categorical", "categorical", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var45", "Var46"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Cruise", "CastType", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "apfilename", "adfilename", "cdomY", "cdomfilename", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var45", "Var46", "Comments"], "EmptyFieldRule", "auto");

% Import the data
LTERsamplelog = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":AU" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    LTERsamplelog = [LTERsamplelog; tb]; %#ok<AGROW>
end

end