function [NESLTERchlmerged, header] = importPythonNESLTERcsv(filename, dataLines)
%IMPORTFILE Import data from a text file
%  NESLTERCHLMERGED = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  NESLTERCHLMERGED = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  NESLTERchlmerged = importfile("C:\data\NESLTER_chl_merged.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Dec-2019 12:14:50

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "cruise", "cast", "niskin", "lter_station", "filter_size", "chl_x", "chl_y", "phaeo_x", "phaeo_y", "LabNB_x", "LabNB_y", "QCflag_x", "QCflag_y", "qc_d_x", "qc_d_y", "comments_x", "comments_y", "abs_z", "z", "ratio"];
opts.SelectedVariableNames = ["cruise", "cast", "niskin", "lter_station", "filter_size", "chl_x", "chl_y", "phaeo_x", "phaeo_y", "LabNB_x", "LabNB_y", "QCflag_x", "QCflag_y", "qc_d_x", "qc_d_y", "comments_x", "comments_y", "abs_z", "z", "ratio"];
opts.VariableTypes = ["string", "string", "double", "double", "string", "double", "double", "double", "double", "double", "string", "string", "double", "double", "double", "double", "categorical", "categorical", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "cruise", "lter_station", "LabNB_x", "LabNB_y"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "cruise", "lter_station", "LabNB_x", "LabNB_y", "comments_x", "comments_y"], "EmptyFieldRule", "auto");

% Import the data
NESLTERchlmerged = readtable(filename, opts);
header = ["cruise", "cast", "niskin", "lter_station", "filter_size", "chl_x", "chl_y", "phaeo_x", "phaeo_y", "LabNB_x", "LabNB_y", "QCflag_x", "QCflag_y", "qc_d_x", "qc_d_y", "comments_x", "comments_y", "abs_z", "z", "ratio"];

end