function [NESLTERchl,header] = importNESLTERchlxlsALL(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  NESLTERCHL = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  NESLTERCHL = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  NESLTERCHL = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  NESLTERchl = importfile("\\sosiknas1\Lab_data\LTER\CHL\NESLTERchl.xlsx", "chl", [1, 2215]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Dec-2019 14:39:30

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 6000];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 35);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":AI" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Cruise", "Date", "LTERStation", "Cast", "Niskin", "TimeIn", "TimeOut", "Replicate", "VolFilt", "FilterSize", "VolExtracted", "Sample", "Acetone", "DilutionDuringReading", "Chl_Cal_Filename", "tau_Calibration", "Fd_Calibration", "Rb", "Ra", "blank", "Rbblank", "Rablank", "Chlugl", "Phaeougl", "Cal_Date", "LabnotebookandPagenumber", "Date_analyzed", "cruise_project_type", "PersonnelFilter", "PersonnelRead", "Fluorometer", "quality_flag", "QC_d", "Comments", "Comments2"];
opts.VariableTypes = ["categorical", "double", "string", "double", "double", "datetime", "datetime", "string", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string",                                                                 "double", "double", "string", "categorical", "categorical", "double", "double", "string", "string",];

% Specify variable properties
opts = setvaropts(opts, ["LTERStation", "Replicate", "LabnotebookandPagenumber", "PersonnelFilter", "Comments", "Comments2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Cruise", "LTERStation", "Replicate", "Chl_Cal_Filename", "LabnotebookandPagenumber", "cruise_project_type", "PersonnelFilter", "PersonnelRead", "Fluorometer", "Comments", "Comments2"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "TimeIn", "InputFormat", "");
opts = setvaropts(opts, "TimeOut", "InputFormat", "");

% Import the data
NESLTERchl = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":AI" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    NESLTERchl = [NESLTERchl; tb]; %#ok<AGROW>
end
header = ["Cruise", "Date", "LTERStation", "Cast", "Niskin", "TimeIn", "TimeOut", "Replicate", "VolFilt", "FilterSize", "VolExtracted", "Sample", "Acetone", "DilutionDuringReading", "Chl_Cal_Filename", "tau_Calibration", "Fd_Calibration", "Rb", "Ra", "blank", "Rbblank", "Rablank", "Chlugl", "Phaeougl", "Cal_Date", "LabnotebookandPagenumber", "Date_analyzed", "cruise_project_type", "PersonnelFilter", "PersonnelRead", "Fluorometer", "quality_flag", "QC_d", "Comments", "Comments2"];
end