function NESLTERchl = import_NESLTERchl(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  NESLTERCHL = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  NESLTERCHL = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  NESLTERCHL = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  NESLTERchl = importfile("\\sosiknas1\lab_data\LTER\CHL\NESLTERchl.xlsx", "chl", [2, 2886]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-May-2022 17:05:33

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 2886];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 35);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":AI" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Cruise", "Date", "LTERStation", "Cast", "Niskin", "Var6", "Var7", "Replicate", "Var9", "FilterSize", "Var11", "Var12", "Var13", "DilutionDuringReading", "Chl_Cal_Filename", "tau_Calibration", "Fd_Calibration", "Rb", "Ra", "blank", "Var21", "Var22", "Chlugl", "Phaeougl", "Cal_Date", "LabnotebookandPagenumber", "Date_analyzed", "Var28", "Var29", "Var30", "Fluorometer", "quality_flag", "QC_d", "Comments", "Comments2"];
opts.SelectedVariableNames = ["Cruise", "Date", "LTERStation", "Cast", "Niskin", "Replicate", "FilterSize", "DilutionDuringReading", "Chl_Cal_Filename", "tau_Calibration", "Fd_Calibration", "Rb", "Ra", "blank", "Chlugl", "Phaeougl", "Cal_Date", "LabnotebookandPagenumber", "Date_analyzed", "Fluorometer", "quality_flag", "QC_d", "Comments", "Comments2"];
opts.VariableTypes = ["categorical", "double", "string", "double", "double", "char", "char", "categorical", "char", "double", "char", "char", "char", "double", "categorical", "double", "double", "double", "double", "double", "char", "char", "double", "double", "double", "categorical", "double", "char", "char", "char", "categorical", "double", "double", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["LTERStation", "Var6", "Var7", "Var9", "Var11", "Var12", "Var13", "Var21", "Var22", "Var28", "Var29", "Var30", "Comments", "Comments2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Cruise", "LTERStation", "Var6", "Var7", "Replicate", "Var9", "Var11", "Var12", "Var13", "Chl_Cal_Filename", "Var21", "Var22", "LabnotebookandPagenumber", "Var28", "Var29", "Var30", "Fluorometer", "Comments", "Comments2"], "EmptyFieldRule", "auto");

% Import the data
NESLTERchl = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":AI" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    NESLTERchl = [NESLTERchl; tb]; %#ok<AGROW>
end

end