function HPLC = importHPLC_fromGoddard(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  SOSIK0815REPORT = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  SOSIK0815REPORT = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  SOSIK0815REPORT = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Sosik0815report = importfile("\\sosiknas1\Lab_data\LTER\HPLC\data\Sosik 08-15 report.xlsx", "Report", [10, 141]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Dec-2019 14:53:55

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [10, 400];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 65);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":BM" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["GSFCLabsamplecode", "PI", "SampleLabel", "CruiseID", "Indicateiffiltersarereplicates", "Volumefilteredml", "Station", "BottleNumber", "SamplingDepthmeters", "TotalWaterDepthmeters", "NameofWaterBody", "Year", "Month", "DayofGregorianMonth", "SequentialDayofYear", "GMTTime", "Longitude", "Latitude", "Filtertype", "FilterDiametermm", "FilterstoragebeforeshippingtoGSFC", "Tot_Chl_a", "Tot_Chl_b", "Tot_Chl_c", "Alpha_beta_Car", "Butfuco", "Hexfuco", "Allo", "Diadino", "Diato", "Fuco", "Perid", "Zea", "MV_Chl_a", "DV_Chl_a", "Chlide_a", "MV_Chl_b", "DV_Chl_b", "Chlc1c2", "Chl_c3", "Lut", "Neo", "Viola", "Phytin_a", "Phide_a", "Pras", "Gyro", "TChl", "PPC", "PSC", "PSP", "TCar", "TAcc", "TPg", "DP", "TAccTchla", "PSCTCar", "PPCTCar", "TChlTCar", "PPCTpg", "PSPTPg", "TChlaTPg", "comments", "other", "other1"];
opts.VariableTypes = ["string", "categorical", "string", "categorical", "categorical", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "double", "categorical", "double", "double", "categorical", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "categorical", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["GSFCLabsamplecode", "SampleLabel"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["GSFCLabsamplecode", "PI", "SampleLabel", "CruiseID", "Indicateiffiltersarereplicates", "NameofWaterBody", "Month", "GMTTime", "Filtertype", "FilterstoragebeforeshippingtoGSFC", "comments", "other", "other1"], "EmptyFieldRule", "auto");

% Import the data
HPLC = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":BM" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    HPLC = [HPLC; tb]; %#ok<AGROW>
end

end