function MVCO_CHN_reps = import_MVCO_CHN_fromAccess(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MVCO_CHN_REPS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  MVCO_CHN_REPS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  MVCO_CHN_reps = importfile("C:\data\mvcodata\MVCO_CHN_fromAccess.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Jun-2025 13:33:57

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Event_Number", "Event_Number_Niskin", "Start_Date", "Start_Time_UTC", "Latitude", "Longitude", "Depth", "CHN_sample_ID", "Replicate", "Date_Combusted", "Date_Analyzed", "umol_N", "umol_C", "CHN_blank", "CHN_a", "CHN_amt_filt_a", "CHN_b", "CHN_amt_filt_b", "N_quality_flag", "C_quality_flag", "Notes"];
opts.VariableTypes = ["string", "string", "datetime", "datetime", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Event_Number", "Event_Number_Niskin", "Notes"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Event_Number", "Event_Number_Niskin", "Replicate", "CHN_blank", "Notes"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Start_Date", "InputFormat", "MM/dd/yyyy");
opts = setvaropts(opts, "Start_Time_UTC", "InputFormat", "HH:mm");

% Import the data
MVCO_CHN_reps = readtable(filename, opts);

end